// our-domain.com/

import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { MeetupList } from "@/components";
import { MeetupData } from "@/util/models/meetup-data";

interface HomePageProps {
  meetups: MeetupData[];
}

const HomePage: NextPage<HomePageProps> = ({ meetups }) => {
  return (
    <>
      <Head>
        <title>NextJS Meetups</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <MeetupList meetups={meetups} />
      </main>
    </>
  );
};

// Reserved function by next js for STATIC SITE GENERATION (SSG)
export const getStaticProps: GetStaticProps = async () => {
  // Fetch data
  const DUMMY_MEETUPS = [
    new MeetupData(
      "meet1",
      "Meetup 1",
      "https://cdn.pixabay.com/photo/2023/03/25/09/51/cat-7875506_1280.jpg",
      "Some address 24, 1",
      "First meetup description"
    ),
    new MeetupData(
      "meet2",
      "Meetup 2",
      "https://cdn.pixabay.com/photo/2023/03/23/12/53/duck-7871855_1280.jpg",
      "Some address 1231, 12 Fake City",
      "Second meetup description"
    ),
  ];

  // Return as props for our page component

  // You can make it Incremental Static Regeneration (ISR)
  // adding revalidate: (value)
  // Will be regenerated every 10 seconds if there's requests on the page (IRS)
  return {
    props: {
      meetups: JSON.parse(JSON.stringify(DUMMY_MEETUPS)),
    },
    revalidate: 10,
  };
};

export default HomePage;
